// @ts-nocheck
import React, { useState } from "react";

const FAQItem = ({ faq, index, isOpen, toggleOpen }) => {
  return (
    <div 
      className={`rwp-faq-item ${isOpen ? "is-open" : ""}`} 
      onMouseEnter={() => {}}
    >
      {/* 1. Back Folder */}
      <div className="faq-back">
        <div className="faq-tab">
          {faq.shortTitle || `0${index + 1}`}
        </div>
        <div className="faq-back-body"></div>
      </div>
      
      {/* 2. Paper Document (Answer) */}
      <div className="faq-paper-wrapper">
        <div className="faq-paper">
          <p className="faq-answer-text">{faq.answer}</p>
        </div>
      </div>
      
      {/* 3. Front Folder (Question) */}
      <div className="faq-front" onClick={() => toggleOpen(index)}>
        <h4 className="faq-question-text">{faq.question}</h4>
        <div className="faq-icon">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
            <path d="M12 5v14M5 12h14" />
          </svg>
        </div>
      </div>
    </div>
  );
};

export const FAQSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleOpen = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const FAQS = [
    {
      shortTitle: "Platform",
      question: "Is Ride With Pals only for professional cycling clubs?",
      answer: "Not at all! Whether you are a casual weekend rider, a solo explorer, or a massive 500-member community club, our platform scales to fit your exact needs. Start for free on the Rider plan and upgrade as your club grows."
    },
    {
      shortTitle: "Devices",
      question: "Is the platform mobile-friendly and responsive?",
      answer: "Absolutely. Our app and dashboard adapt beautifully to all screen sizes, including desktops, tablets, and smartphones. Every section is designed to deliver a seamless experience across devices while you're on the go."
    },
    {
      shortTitle: "Billing",
      question: "Are there any hidden fees or setup costs?",
      answer: "No setup costs and no hidden fees. All of our paid plans come with a straightforward monthly or yearly subscription, and they all include a 14-day free trial so you can make sure it's the right fit for your club."
    },
    {
      shortTitle: "Support",
      question: "Do you offer priority support for Elite clubs?",
      answer: "Yes, our Elite Club plan includes priority onboarding and 24/7 dedicated support to ensure your large-scale club operations, wallet management, and custom leaderboards run without a hitch."
    },
    {
      shortTitle: "Customization",
      question: "Can I change the colors and branding for my club?",
      answer: "Absolutely! Elite and Pro clubs can upload their own logos, choose custom accent colors, and personalize the dashboard to ensure the app feels like a true extension of your community."
    },
    {
      shortTitle: "Data Privacy",
      question: "Who owns the data generated by my club's riders?",
      answer: "You do. We believe in complete data sovereignty. Your club's ride data, member information, and analytics are 100% owned by you. We never sell your data to third-party advertisers."
    }
  ];

  const css = `
    .rwp-faq-section {
      padding: 120px 40px;
      background: transparent;
      position: relative;
      z-index: 1;
    }

    /* Full Width Container */
    .rwp-faq-container {
      max-width: 1200px;
      margin: 0 auto;
      display: flex;
      flex-direction: column;
    }

    /* ─── Top: Header & Image Collage ─── */
    .rwp-faq-header {
      display: flex;
      flex-direction: column;
      gap: 60px;
      margin-bottom: 100px;
      width: 100%;
    }
    .rwp-faq-header-text {
      text-align: left;
    }
    .rwp-faq-title {
      font-family: Manrope, Inter, sans-serif;
      font-size: clamp(36px, 4vw, 56px);
      font-weight: 800;
      color: #fff;
      line-height: 1.1;
      margin-bottom: 24px;
      letter-spacing: -0.03em;
    }
    .rwp-faq-title span {
      color: #EB712B;
    }
    .rwp-faq-subtitle {
      font-family: Manrope, Inter, sans-serif;
      font-size: 16px;
      color: rgba(255,255,255,0.4);
      line-height: 1.6;
      margin-bottom: 0;
      max-width: 480px;
    }

    /* Collage (Right side of header) */
    .rwp-faq-collage {
      position: relative;
      height: 380px;
      width: 100%;
      max-width: 700px;
    }
    .rwp-faq-collage-img {
      position: absolute;
      border-radius: 16px;

      object-fit: cover;
    }

    .img-book {
      width: 65%;
      height: 260px;
      top: 0;
      left: 0;
      z-index: 1;
      border: 1px solid rgba(255,255,255,0.05);
    }
    .img-thinking {
      width: 55%;
      height: 340px;
      bottom: 10px;
      right: 10px;
      z-index: 3;

    }
    .img-question {
      width: 110px;
      height: 110px;
      top: 200px;
      left: 30px;
      z-index: 2;
      border-radius: 50%;
      border: 4px solid #050505;
      background: #111;
      padding: 10px;
    }

    /* ─── Bottom: Folder Accordions ─── */
    .rwp-faq-list {
      display: flex;
      flex-direction: column;
      gap: 32px;
      width: 100%;
      max-width: 1000px;
      margin: 0 auto; /* Centered */
    }

    /* ─── Intricate Folder Logic ─── */
    
    .rwp-faq-item {
      position: relative;
      width: 100%;
      display: flex;
      flex-direction: column;
      /* GPU acceleration */
      transform: translateZ(0); 
    }

    /* 1. Back Folder (Static) */
    .faq-back {
      position: relative;
      z-index: 1;
      display: flex;
      flex-direction: column;
    }
    .faq-tab {
      align-self: flex-start;
      background: #111;
      padding: 12px 28px;
      border-radius: 12px 12px 0 0;
      font-family: Manrope, Inter, sans-serif;
      font-size: 13px;
      font-weight: 700;
      color: rgba(255,255,255,0.5);
      text-transform: uppercase;
      letter-spacing: 0.1em;
      border: 1px solid rgba(255,255,255,0.1);
      border-bottom: none;
      /* The connecting curve */
      position: relative;
    }
    .faq-tab::after {
      content: '';
      position: absolute;
      bottom: 0;
      right: -16px;
      width: 16px;
      height: 16px;
      background: transparent;
      border-bottom-left-radius: 12px;
      box-shadow: -8px 8px 0 0 #111;
    }
    .faq-back-body {
      background: #111;
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: 0 16px 16px 16px;
      height: 40px; /* Just tall enough to connect the tab */
      width: 100%;
      margin-top: -1px;
    }

    /* 2. Paper Document (Middle Layer) */
    .faq-paper-wrapper {
      position: relative;
      z-index: 2;
      width: calc(100% - 16px);
      margin: 0 auto;
      
      /* Animation using grid */
      display: grid;
      grid-template-rows: 0fr;
      transition: grid-template-rows 0.4s cubic-bezier(0.16, 1, 0.3, 1), transform 0.4s;
      
      /* Base state (hidden behind front folder) */
      margin-top: -24px; 
    }
    
    .faq-paper {
      overflow: hidden;
      background: #fafafa;
      border-radius: 8px 8px 0 0;
      /* On hover, add a white border/shadow to act as the "peek" */
      box-shadow: 0 -8px 0 #fafafa;
      transform: translateY(20px); /* hide the shadow initially by tucking it under the tab */
      transition: transform 0.3s;
    }
    .rwp-faq-item:hover .faq-paper {
      transform: translateY(12px); /* peek out! */
    }
    .rwp-faq-item.is-open .faq-paper {
      transform: translateY(0);
      box-shadow: none;
    }
    
    .rwp-faq-item.is-open .faq-paper-wrapper {
      grid-template-rows: 1fr;
      margin-top: -16px; /* Space between tab and paper */
    }
    .faq-answer-text {
      font-family: Manrope, Inter, sans-serif;
      font-size: 16px;
      color: #111; /* Dark text on light paper */
      line-height: 1.6;
      padding: 32px 32px 40px 32px;
      margin: 0;
    }

    /* 3. Front Folder (Question Layer) */
    .faq-front {
      position: relative;
      z-index: 3;
      background: #1a1a1a;
      border: 1px solid rgba(255,255,255,0.12);
      border-radius: 0 16px 16px 16px;
      padding: 24px 32px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 20px;
      cursor: pointer;
      box-shadow: 0 -4px 16px rgba(0,0,0,0.4);
      
      margin-top: -16px; /* Overlap the back body */
      transition: transform 0.4s cubic-bezier(0.16, 1, 0.3, 1), background 0.3s, border-color 0.3s, border-radius 0.3s;
    }
    
    /* Hover State: Front folder slides down */
    .rwp-faq-item:hover .faq-front {
      transform: translateY(8px);
      background: #222;
      border-color: rgba(235,113,43,0.3);
    }
    
    /* Open State: Front folder slides down completely below the paper */
    .rwp-faq-item.is-open .faq-front {
      transform: translateY(0);
      background: #EB712B;
      border-color: #EB712B;
      border-radius: 0 0 16px 16px;
      box-shadow: 0 10px 30px rgba(235,113,43,0.2);
    }

    .faq-question-text {
      font-family: Manrope, Inter, sans-serif;
      font-size: 19px;
      font-weight: 700;
      color: #fff;
      margin: 0;
      line-height: 1.4;
      transition: color 0.3s;
    }

    /* Icon */
    .faq-icon {
      color: rgba(255,255,255,0.4);
      transition: transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275), color 0.3s;
      flex-shrink: 0;
    }
    .rwp-faq-item:hover .faq-icon {
      color: #EB712B;
    }
    .rwp-faq-item.is-open .faq-icon {
      transform: rotate(135deg);
      color: #fff;
    }


    /* Responsive */
    @media (max-width: 992px) {
      .rwp-faq-header {
        grid-template-columns: 1fr;
        text-align: center;
        gap: 40px;
      }
      .rwp-faq-header-text {
        text-align: center;
      }
      .rwp-faq-subtitle {
        margin: 0 auto;
      }
      .rwp-faq-collage {
        max-width: 500px;
        margin: 0 auto;
      }
    }
    @media (max-width: 600px) {
      .faq-front { padding: 20px; }
      .faq-answer-text { padding: 24px; font-size: 15px; }
      .faq-question-text { font-size: 16px; }
      .img-book { width: 75%; height: 200px; }
      .img-thinking { width: 60%; height: 160px; right: 0; bottom: 40px; }
      .img-question { width: 80px; height: 80px; top: 150px; left: 10px; }
    }
  `;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <section className="rwp-faq-section" id="faq">
        <div className="rwp-faq-container">
          
          {/* Top Header Section */}
          <div className="rwp-faq-header">
            <div className="rwp-faq-header-text">
              <h2 className="rwp-faq-title">
                Got questions?<br />
                <span>We’ve got answers.</span>
              </h2>
              <p className="rwp-faq-subtitle">
                Here’s everything you need to know before getting started. If you have more questions, feel free to reach out to our team.
              </p>
            </div>

            <div className="rwp-faq-collage">
              <img 
                src="/Images/FAQ-book.jpg" 
                alt="Open notebook for FAQ" 
                className="rwp-faq-collage-img img-book" 
                loading="lazy"
              />
              <img 
                src="/Images/person-thinking.png" 
                alt="Person thinking about questions" 
                className="rwp-faq-collage-img img-thinking" 
                loading="lazy"
              />
              <img 
                src="/Images/question-mark.png" 
                alt="Question mark bubble" 
                className="rwp-faq-collage-img img-question" 
                loading="lazy"
              />
            </div>
          </div>

          {/* Bottom Accordion Section */}
          <div className="rwp-faq-list">
            {FAQS.map((faq, index) => (
              <FAQItem 
                key={index} 
                faq={faq} 
                index={index} 
                isOpen={openIndex === index} 
                toggleOpen={toggleOpen} 
              />
            ))}
          </div>

        </div>
      </section>
    </>
  );
};
